### ISSUE TITLE
App theme option in preferences

### ISSUE THREAD

**Issue by marcogenovese** [jahirfiquitiva/IconShowcase-Dashboard#10]
Sorry I don't know if someone ask this feature before but I think it could be nice for developer to have this option and for users to have a choice in preferences to switch light/dark theme . I know that needs work and some of your time, so no problem at all. Thank you for this great dashboard.

**Comment by jahirfiquitiva** [comment]
Thanks for the suggestion. Previous versions included it, but users don't use it that much, so I removed it.

It might be back for next update.
