### ISSUE TITLE
Kustom cards become transparent when device orientation changes

### ISSUE THREAD

**Issue by marcogenovese** [jahirfiquitiva/IconShowcase-Dashboard#11]
I found 2 bug:
For example if I have 6 item in kustom widgets
1)If I rotate my device to landscape orientation widgets lost the backgroud and cards become fully transparent
2)There is always a widget sometimes on the first row, sometimes the second, that isn't aligned to the others

**Comment by jahirfiquitiva** [comment]
1) Can you add a picture?
2) The issue comes from a library I'm using for the sectioned recyclerview, and I can't do anything for now. I plan to use something different in future updates.

**Comment by marcogenovese** [comment]
starting portrait - landscape - back to portrait
![screenshot_20170617-173502](https://user-images.githubusercontent.com/27960197/27254892-74e0a84c-5392-11e7-962b-73c29e2212bf.png)
![screenshot_20170617-173517](https://user-images.githubusercontent.com/27960197/27254895-78258a9a-5392-11e7-9fd9-56a125be5b34.png)
![screenshot_20170617-173527](https://user-images.githubusercontent.com/27960197/27254896-7bc56df0-5392-11e7-9a44-89c3c1fabb76.png)

**Comment by jahirfiquitiva** [comment]
Thank you. I will keep this in mind for a future update.

**Comment by marcogenovese** [comment]
I have fixed the alignment bug. Simply setting (position<spanCount) on SectionedGridSpacingItemDecoration.java

**Comment by AllanWang** [comment]
Closed as PR has been merged.

**Comment by marcogenovese** [comment]
There is still the rotate bug
