### ISSUE TITLE
drawer header image

### ISSUE THREAD

**Issue by marcogenovese** [jahirfiquitiva/IconShowcase-Dashboard#12]
I have changed drawer_header png and I got an ugly stretched image, I can crop my image to fit the same aspect ratio but I think it should be better to set the scaleType to centerCrop

**Comment by marcogenovese** [comment]
I checked on IconShowcase library and I found mini_drawer_header.xml. I saw that imageView is set correctly. So I build the original IconShowcase-dashborad with just a different drawer_header.png but the issue is still there.. so I think it's a bug

**Comment by jahirfiquitiva** [comment]
You're the first one to complain about this, honestly.

I am using [Material Drawer](https://github.com/mikepenz/MaterialDrawer), so the drawer header comes directly from there, and I cannot modify it.

About the mini header, yeah, is a custom view, so it has that, but the original view doesn't.

For now, create a picture in 16:9 aspect ratio.

I don't think is a really big issue, but I will keep it in mind for a future release.

**Comment by marcogenovese** [comment]
Done.
My pull request was merged.
https://github.com/mikepenz/MaterialDrawer/pull/1913

**Comment by jahirfiquitiva** [comment]
Great. Thank you. I will be sure to update Material Drawer on next IconShowcase version.
