### ISSUE TITLE
No donation section in navigation drawer.

### ISSUE THREAD

**Issue by devesh796** [jahirfiquitiva/IconShowcase-Dashboard#14]
![screenshot_20170710-212258](https://user-images.githubusercontent.com/15872393/28027620-4e061ac2-65b7-11e7-9242-b64c0e0f874a.jpg)

How do i get the donation section in my app ?

**Comment by jahirfiquitiva** [comment]
[Read the wiki](https://github.com/jahirfiquitiva/IconShowcase-Dashboard/wiki/Adding-donations-option)
