### ISSUE TITLE
Dynamic Calendar Icons

### ISSUE THREAD

**Issue by Sylvia-Keren-Happuch** [jahirfiquitiva/IconShowcase-Dashboard#15]
How can I make dynamic calendar icons? For example, on August 1 there should be a 1, on August 2 there should be a 2, ... and on August 31 there should be a 31 (see pic).
![31](https://user-images.githubusercontent.com/28256260/28535740-c0e6aa04-70a5-11e7-8999-261c9dbc2d7e.png)

**Comment by Gowsky** [comment]
Check here http://bfy.tw/D0PL
