### ISSUE TITLE
Error (35, 0)

### ISSUE THREAD

**Issue by mazlum298** [jahirfiquitiva/IconShowcase-Dashboard#17]
I update something on studio and java to latest version, now it show me that problem 

`Error:(35, 0) Cannot set the value of read-only property 'outputFile' for ApkVariantOutputImpl_Decorated{apkData=Main{type=MAIN, fullName=debug, filters=[]}} of type com.android.build.gradle.internal.api.ApkVariantOutputImpl.`

what can I do for that ?

**Comment by jahirfiquitiva** [comment]
Remove lines [33](https://github.com/jahirfiquitiva/IconShowcase-Dashboard/blob/master/sample/build.gradle#L33) to [38](https://github.com/jahirfiquitiva/IconShowcase-Dashboard/blob/master/sample/build.gradle#L38) from the [`sample/build.gradle`](https://github.com/jahirfiquitiva/IconShowcase-Dashboard/blob/master/sample/build.gradle) file

And kindly wait for next release, which is going to be big.

If that doesn't solve the issue. Please revert and stay with Android Studio 2.3.3 and gradle tools 2.3.3 for now.

There's no real need to update unless you are developing other apps that require this.

**Comment by jahirfiquitiva** [comment]
You can join the [Google+ community](https://plus.google.com/communities/117748118619432374563) to stay tuned about the next update

**Comment by mazlum298** [comment]
thanks for helping, I try it but dont solve problem give me one more issue (33, 0) I wıll back to 2.3.3.
