### ISSUE TITLE
Doesn't work on lower androids version

### ISSUE THREAD

**Issue by puredesigndev** [jahirfiquitiva/IconShowcase-Dashboard#20]
App seems to not being able to install on lower version of android, despite the fact I have set "minimum sdk=16 ". Did i something wrong ?
On nexus 5x which has android 8.1 and samsung A5 which has android 7.0 works good

**Comment by omekurnia** [comment]
Maybe you can provide the logcat to see the problem clearly

**Comment by puredesigndev** [comment]
Actually I can generate signed app, but when i transfer it on phone with android 6.0 or less, it pops up that app cannot be installed

**Comment by puredesigndev** [comment]
So im not able to install the *.apk on phone with android 6.0 and less

**Comment by omekurnia** [comment]
Did you try to direct debug with your older android phone instead sending apk.

As far as I know, you can not install a debug apk on another phone if you transfer it from your debug phone.

**Comment by puredesigndev** [comment]
no i didn't .

i'll try

**Comment by puredesigndev** [comment]
hmm . 
I did "debug 'app" in android studio by a few created devices similar to mine (API), then
i generate signed app, as release, send apk to my phone and still, i can't install it on my devices.
It shows that "app hasn't benn installed "

**Comment by puredesigndev** [comment]
generate signed apk "release" then send to "physical phone"

**Comment by jahirfiquitiva** [comment]
Make sure you use the v1 and v2 signing. This issue is **not** related to IconShowcase

**Comment by puredesigndev** [comment]
great it works ,
thank you

when i will publish it on google play
i also have to use both (v1 and v2) ??

**Comment by omekurnia** [comment]
Yes, ultimately.

**Comment by jahirfiquitiva** [comment]
@puredesigndev 

Yes, always use v1 and v2. It just adds some extra protection plus other improvements to the apk while keeping the backwards compatibility.

It is good to use both and it won't affect the apk in a bad way.
