### ISSUE TITLE
6 Errors Occuring

### ISSUE THREAD

**Issue by Technologx** [jahirfiquitiva/IconShowcase-Dashboard#3]
I'm running into some errors and I'm not sure what to do to fix them. I'm new to the Android theming DOD Graphics told me about it.
https://ghostbin.com/paste/mnxgx﻿

**Comment by jahirfiquitiva** [comment]
Make sure you don't remove strings and rebuild the project.

If still fails, close AS and try again.﻿

This is AS related issues which must be solved by yourselves.
