### ISSUE TITLE
icon request shows all apps

### ISSUE THREAD

**Issue by ryder203** [jahirfiquitiva/IconShowcase-Dashboard#4]
Icon request function shows all apps in v1.9.6.1.
Only icons without declared icon should be shown.

**Comment by jahirfiquitiva** [comment]
Be sure you added the appfilter in raw folder.
I'm confident the icon request function is workin properly.

**Comment by ryder203** [comment]
Oh, my bad. Sorry for noobin around. Thank you. Much respect for your work, Sir.
