### ISSUE TITLE
Configuring App Part 2

### ISSUE THREAD

**Issue by ErraticFox** [jahirfiquitiva/IconShowcase-Dashboard#5]
I've never made a app before, so forgive me. In Part 2 of Configuring App, you don't tell us what file these strings are located in / go into.

**Comment by jahirfiquitiva** [comment]
`src/main/res/values/strings.xml`

**Comment by Luismi74** [comment]
where is the home_configuraton.xml?

**Comment by jahirfiquitiva** [comment]
@Luismi74 
Don't spam with your questions, in other issues reports.
You gotta wait until I answer, otherwise try to find the answer by yourself.
