### ISSUE TITLE
Wallpaper function crashing if called from settings

### ISSUE THREAD

**Issue by ryder203** [jahirfiquitiva/IconShowcase-Dashboard#6]
Going to settings, choosing wallpaper from there off the wallpaper section crashes the app when tapping on a wallpaper. Choosing a wallpaper from the app works if the app is launched from homescreen. Log attached.
[2016-09-04-10-27-44.txt](https://github.com/jahirfiquitiva/IconShowcase-Dashboard/files/453832/2016-09-04-10-27-44.txt)

**Comment by jahirfiquitiva** [comment]
What do you mean with "called from settings"?
Also, please mention some info about your device. Model, manufacturer, android version, rom, screen size, dpi, etc.

**Comment by ryder203** [comment]
OnePlus 3, oxygen OS, Android 6 / I enter settings, go to section "display" go to background/wallpaper, choose not gallery or others but the icon dashboard app, the app opens it wallpaper tab, wallpaper is tapped, icon dashboard silent FC.

**Comment by jahirfiquitiva** [comment]
Is wallpaper applied or the app fc just before that?

**Comment by ryder203** [comment]
Nope, silent FC before any further action or process possible.

**Comment by jahirfiquitiva** [comment]
Thanks for the info, will keep it in mind for next update.

**Comment by ryder203** [comment]
Hi Jahir. Here the FC message.
`com.afollestad.materialdialogs.MaterialDialog$DialogException: Bad window token, you cannot show a dialog before an Activity is created or after it's hidden.
	at com.afollestad.materialdialogs.MaterialDialog.show(Unknown Source)
	at com.afollestad.materialdialogs.MaterialDialog$Builder.show(Unknown Source)
	at jahirfiquitiva.iconshowcase.fragments.WallpapersFragment.showApplyWallpaperDialog(Unknown Source)
	at jahirfiquitiva.iconshowcase.fragments.WallpapersFragment.access$000(Unknown Source)
	at jahirfiquitiva.iconshowcase.fragments.WallpapersFragment$1$1.onClick(Unknown Source)
	at jahirfiquitiva.iconshowcase.adapters.WallpapersAdapter$WallsHolder.onClick(Unknown Source)
	at android.view.View.performClick(View.java:5280)
	at android.view.View$PerformClick.run(View.java:21239)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:234)
	at android.app.ActivityThread.main(ActivityThread.java:5526)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by jahirfiquitiva** [comment]
Thanks

**Comment by AllanWang** [comment]
I will be reworking all the dialogs. This should no longer be an issue.

**Comment by jahirfiquitiva** [comment]
Thank you so much Allan 😊

**Comment by ryder203** [comment]
So just for my understanding; the fix by AllanWang from some hours ago would need to be merged from "IconShowcase" to "IconShowcase-Dashboard" so gradle build process pulls the needed files from the git when making a build in Android Studio? Could you explain how this works? How would I get the fix so my app does not FC anymore? Or do I need to fix the files locally? Excuse me, but things are not really clear to me as I am a beginner.

**Comment by jahirfiquitiva** [comment]
Changes need to be done in IconShowcase, but they won't be public until update is finished.

Which means you have to wait some time for update. That could be weeks or even months.

Allan and I are going to university and don't have that much free time.

About the update process, that's explained in the wiki, but as there won't be any update anytime soon, you shouldn't worry for now.

You can join the Google+ community to stay tuned about the updates and stuff.

**Comment by jahirfiquitiva** [comment]
If you want to take the source and edit it and fix the issue for yourself, you can do it. But I don't recommend it as you said you're a beginner and you will get into more issues, and I won't help when doing it. (Check README file).

**Comment by ryder203** [comment]
OK, thanks for your patience.

**Comment by AllanWang** [comment]
Yep, as mentioned, you can get all the updates by changing the gradle dependency. But since I've gotten on editing, we've been reworking a lot of stuff and a big portion of the app is not 100% functional as it is being rewritten. It will take a while but we can guarantee that it will be better and whatever issues left will be easier to fix. If you know other devs, they can feel free to fork and contribute, but if you aren't a developer just wait until we actually push an official release. I've already (somewhat) fixed this crash so I'm going to close it here.
