### ISSUE TITLE
Error On OnePlus 3T

### ISSUE THREAD

**Issue by lohigno** [jahirfiquitiva/IconShowcase-Dashboard#8]
Problem detected on Google Play Developer 👍 
Versione applicazione
8
Versione di Android
Android 7.1
Dispositivo
OnePlus3T (OnePlus3T)
Produttore Oneplus RAM (MB) 6144 Dimensioni schermo 1080 × 1920 Densità schermo (dpi) 480 Piattaforma nativa armeabi-v7a Versione OpenGL ES 3.1 Marca CPU Qualcomm Modello CPU MSM8996

"Signal Catcher" daemon prio=5 tid=3 Runnable
  | group="system" sCount=0 dsCount=0 obj=0x12cb1310 self=0x7f9fe97400
  | sysTid=15984 nice=0 cgrp=default sched=0/0 handle=0x7f9f39c450
  | state=R schedstat=( 36563961 10125884 80 ) utm=0 stm=2 core=1 HZ=100
  | stack=0x7f9f2a2000-0x7f9f2a4000 stackSize=1005KB
  | held mutexes= "mutator lock"(shared held)
  native: pc 00000000004cf6dc  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+220)
  native: pc 00000000004cf6d8  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+216)
  native: pc 00000000004a2068  /system/lib64/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+480)
  native: pc 00000000004ba534  /system/lib64/libart.so (_ZN3art14DumpCheckpoint3RunEPNS_6ThreadE+856)
  native: pc 00000000004b28c4  /system/lib64/libart.so (_ZN3art10ThreadList13RunCheckpointEPNS_7ClosureE+448)
  native: pc 00000000004b24d0  /system/lib64/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEb+860)
  native: pc 00000000004b2130  /system/lib64/libart.so (_ZN3art10ThreadList14DumpForSigQuitERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+808)
  native: pc 000000000048c898  /system/lib64/libart.so (_ZN3art7Runtime14DumpForSigQuitERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+192)
  native: pc 000000000049368c  /system/lib64/libart.so (_ZN3art13SignalCatcher13HandleSigQuitEv+2508)
  native: pc 0000000000492048  /system/lib64/libart.so (_ZN3art13SignalCatcher3RunEPv+472)
  native: pc 000000000007684c  /system/lib64/libc.so (_ZL15__pthread_startPv+204)
  native: pc 000000000001e158  /system/lib64/libc.so (__start_thread+16)

"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 obj=0x761ee7f0 self=0x7f9fe96a00
  | sysTid=15978 nice=-10 cgrp=default sched=0/0 handle=0x7fa44b3a98
  | state=S schedstat=( 387325638 57194164 503 ) utm=29 stm=9 core=3 HZ=100
  | stack=0x7fd5947000-0x7fd5949000 stackSize=8MB
  | held mutexes=
  native: pc 0000000000078e28  /system/lib64/libc.so (__epoll_pwait+8)
  native: pc 000000000001e868  /system/lib64/libc.so (epoll_pwait+64)
  native: pc 00000000000183bc  /system/lib64/libutils.so (_ZN7android6Looper9pollInnerEi+160)
  native: pc 0000000000018264  /system/lib64/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+60)
  native: pc 00000000000f1fdc  /system/lib64/libandroid_runtime.so (_ZN7android18NativeMessageQueue8pollOnceEP7_JNIEnvP8_jobjecti+48)
  native: pc 00000000008b98dc  /data/dalvik-cache/arm64/system@framework@boot-framework.oat (Java_android_os_MessageQueue_nativePollOnce__JI+140)
  at android.os.MessageQueue.nativePollOnce (Native method)
  at android.os.MessageQueue.next (MessageQueue.java:323)
  at android.os.Looper.loop (Looper.java:136)
  at android.app.ActivityThread.main (ActivityThread.java:6178)
  at java.lang.reflect.Method.invoke! (Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:891)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:781)

"Jit thread pool worker thread 0" daemon prio=5 tid=2 Native
  | group="main" sCount=1 dsCount=0 obj=0x12cb1280 self=0x7f9840e000
  | sysTid=15983 nice=9 cgrp=default sched=0/0 handle=0x7f9f49d450
  | state=S schedstat=( 118707921 212236401 323 ) utm=9 stm=2 core=1 HZ=100
  | stack=0x7f9f39f000-0x7f9f3a1000 stackSize=1021KB
  | held mutexes=
  native: pc 000000000001bd2c  /system/lib64/libc.so (syscall+28)
  native: pc 00000000000e99d0  /system/lib64/libart.so (_ZN3art17ConditionVariable16WaitHoldingLocksEPNS_6ThreadE+156)
  native: pc 00000000004bc098  /system/lib64/libart.so (_ZN3art10ThreadPool7GetTaskEPNS_6ThreadE+248)
  native: pc 00000000004bb62c  /system/lib64/libart.so (_ZN3art16ThreadPoolWorker3RunEv+144)
  native: pc 00000000004baeec  /system/lib64/libart.so (_ZN3art16ThreadPoolWorker8CallbackEPv+128)
  native: pc 000000000007684c  /system/lib64/libc.so (_ZL15__pthread_startPv+204)
  native: pc 000000000001e158  /system/lib64/libc.so (__start_thread+16)

"FinalizerWatchdogDaemon" daemon prio=5 tid=4 Sleeping
  | group="system" sCount=1 dsCount=0 obj=0x12cb14c0 self=0x7f9fec2e00
  | sysTid=15987 nice=0 cgrp=default sched=0/0 handle=0x7f9f095450
  | state=S schedstat=( 142916 4950990 2 ) utm=0 stm=0 core=2 HZ=100
  | stack=0x7f9ef93000-0x7f9ef95000 stackSize=1037KB
  | held mutexes=
  at java.lang.Thread.sleep! (Native method)
- sleeping on <0x05520d18> (a java.lang.Object)
  at java.lang.Thread.sleep (Thread.java:371)
- locked <0x05520d18> (a java.lang.Object)
  at java.lang.Thread.sleep (Thread.java:313)
  at java.lang.Daemons$FinalizerWatchdogDaemon.sleepFor (Daemons.java:314)
  at java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization (Daemons.java:336)
  at java.lang.Daemons$FinalizerWatchdogDaemon.run (Daemons.java:253)
  at java.lang.Thread.run (Thread.java:761)

"HeapTaskDaemon" daemon prio=5 tid=5 Blocked
  | group="system" sCount=1 dsCount=0 obj=0x12cb1550 self=0x7f9fec3800
  | sysTid=15988 nice=0 cgrp=default sched=0/0 handle=0x7f9ef90450
  | state=S schedstat=( 26959481 20041249 26 ) utm=1 stm=0 core=3 HZ=100
  | stack=0x7f9ee8e000-0x7f9ee90000 stackSize=1037KB
  | held mutexes=
  native: pc 000000000001bd2c  /system/lib64/libc.so (syscall+28)
  native: pc 00000000000e99d0  /system/lib64/libart.so (_ZN3art17ConditionVariable16WaitHoldingLocksEPNS_6ThreadE+156)
  native: pc 000000000026a370  /system/lib64/libart.so (_ZN3art2gc13TaskProcessor7GetTaskEPNS_6ThreadE+276)
  native: pc 000000000026acbc  /system/lib64/libart.so (_ZN3art2gc13TaskProcessor11RunAllTasksEPNS_6ThreadE+92)
  native: pc 00000000001e75dc  /data/dalvik-cache/arm64/system@framework@boot-core-libart.oat (Java_dalvik_system_VMRuntime_runHeapTasks__+124)
  at dalvik.system.VMRuntime.runHeapTasks (Native method)
- waiting to lock an unknown object
  at java.lang.Daemons$HeapTaskDaemon.run (Daemons.java:433)
  at java.lang.Thread.run (Thread.java:761)

"Binder:15978_1" prio=5 tid=6 Native
  | group="main" sCount=1 dsCount=0 obj=0x12cb1670 self=0x7f98414400
  | sysTid=15989 nice=0 cgrp=default sched=0/0 handle=0x7f9ed8d450
  | state=S schedstat=( 2715987 9295937 17 ) utm=0 stm=0 core=3 HZ=100
  | stack=0x7f9ec93000-0x7f9ec95000 stackSize=1005KB
  | held mutexes=
  native: pc 0000000000078f14  /system/lib64/libc.so (__ioctl+4)
  native: pc 000000000002008c  /system/lib64/libc.so (ioctl+140)
  native: pc 0000000000055974  /system/lib64/libbinder.so (_ZN7android14IPCThreadState14talkWithDriverEb+256)
  native: pc 0000000000055adc  /system/lib64/libbinder.so (_ZN7android14IPCThreadState20getAndExecuteCommandEv+24)
  native: pc 00000000000561b8  /system/lib64/libbinder.so (_ZN7android14IPCThreadState14joinThreadPoolEb+64)
  native: pc 00000000000741e0  /system/lib64/libbinder.so (???)
  native: pc 000000000001283c  /system/lib64/libutils.so (_ZN7android6Thread11_threadLoopEPv+328)
  native: pc 00000000000a028c  /system/lib64/libandroid_runtime.so (_ZN7android14AndroidRuntime15javaThreadShellEPv+112)
  native: pc 000000000007684c  /system/lib64/libc.so (_ZL15__pthread_startPv+204)
  native: pc 000000000001e158  /system/lib64/libc.so (__start_thread+16)

"FinalizerDaemon" daemon prio=5 tid=7 Waiting
  | group="system" sCount=1 dsCount=0 obj=0x12cb1430 self=0x7f9fe99200
  | sysTid=15986 nice=0 cgrp=default sched=0/0 handle=0x7f9f19a450
  | state=S schedstat=( 1191200 5888956 9 ) utm=0 stm=0 core=3 HZ=100
  | stack=0x7f9f098000-0x7f9f09a000 stackSize=1037KB
  | held mutexes=
  at java.lang.Object.wait! (Native method)
- waiting on <0x0c7d1371> (a java.lang.Object)
  at java.lang.Object.wait (Object.java:407)
  at java.lang.ref.ReferenceQueue.remove (ReferenceQueue.java:188)
- locked <0x0c7d1371> (a java.lang.Object)
  at java.lang.ref.ReferenceQueue.remove (ReferenceQueue.java:209)
  at java.lang.Daemons$FinalizerDaemon.run (Daemons.java:204)
  at java.lang.Thread.run (Thread.java:761)

"ReferenceQueueDaemon" daemon prio=5 tid=8 Waiting
  | group="system" sCount=1 dsCount=0 obj=0x12cb13a0 self=0x7f9fe98800
  | sysTid=15985 nice=0 cgrp=default sched=0/0 handle=0x7f9f29f450
  | state=S schedstat=( 686926 5469271 12 ) utm=0 stm=0 core=3 HZ=100
  | stack=0x7f9f19d000-0x7f9f19f000 stackSize=1037KB
  | held mutexes=
  at java.lang.Object.wait! (Native method)
- waiting on <0x0793e556> (a java.lang.Class<java.lang.ref.ReferenceQueue>)
  at java.lang.Daemons$ReferenceQueueDaemon.run (Daemons.java:150)
- locked <0x0793e556> (a java.lang.Class<java.lang.ref.ReferenceQueue>)
  at java.lang.Thread.run (Thread.java:761)

"Binder:15978_2" prio=5 tid=9 Native
  | group="main" sCount=1 dsCount=0 obj=0x12cb1700 self=0x7f9ff73a00
  | sysTid=15990 nice=0 cgrp=default sched=0/0 handle=0x7f9ec90450
  | state=S schedstat=( 3189373 5014843 20 ) utm=0 stm=0 core=3 HZ=100
  | stack=0x7f9eb96000-0x7f9eb98000 stackSize=1005KB
  | held mutexes=
  native: pc 0000000000078f14  /system/lib64/libc.so (__ioctl+4)
  native: pc 000000000002008c  /system/lib64/libc.so (ioctl+140)
  native: pc 0000000000055974  /system/lib64/libbinder.so (_ZN7android14IPCThreadState14talkWithDriverEb+256)
  native: pc 0000000000055adc  /system/lib64/libbinder.so (_ZN7android14IPCThreadState20getAndExecuteCommandEv+24)
  native: pc 00000000000561ec  /system/lib64/libbinder.so (_ZN7android14IPCThreadState14joinThreadPoolEb+116)
  native: pc 00000000000741e0  /system/lib64/libbinder.so (???)
  native: pc 000000000001283c  /system/lib64/libutils.so (_ZN7android6Thread11_threadLoopEPv+328)
  native: pc 00000000000a028c  /system/lib64/libandroid_runtime.so (_ZN7android14AndroidRuntime15javaThreadShellEPv+112)
  native: pc 000000000007684c  /system/lib64/libc.so (_ZL15__pthread_startPv+204)
  native: pc 000000000001e158  /system/lib64/libc.so (__start_thread+16)

"Profile Saver" daemon prio=10 tid=10 Native
  | group="system" sCount=1 dsCount=0 obj=0x12cb18b0 self=0x7f98427800
  | sysTid=15991 nice=-10 cgrp=default sched=0/0 handle=0x7f9eb93450
  | state=S schedstat=( 5657552 2808126 16 ) utm=0 stm=0 core=2 HZ=100
  | stack=0x7f9ea99000-0x7f9ea9b000 stackSize=1005KB
  | held mutexes=
  native: pc 000000000001bd2c  /system/lib64/libc.so (syscall+28)
  native: pc 00000000000e99d0  /system/lib64/libart.so (_ZN3art17ConditionVariable16WaitHoldingLocksEPNS_6ThreadE+156)
  native: pc 0000000000358d84  /system/lib64/libart.so (_ZN3art12ProfileSaver3RunEv+312)
  native: pc 000000000035a504  /system/lib64/libart.so (_ZN3art12ProfileSaver21RunProfileSaverThreadEPv+96)
  native: pc 000000000007684c  /system/lib64/libc.so (_ZL15__pthread_startPv+204)
  native: pc 000000000001e158  /system/lib64/libc.so (__start_thread+16)

"Measurement Worker" prio=5 tid=11 TimedWaiting
  | group="main" sCount=1 dsCount=0 obj=0x12d1df70 self=0x7f9ff1e400
  | sysTid=15995 nice=0 cgrp=default sched=0/0 handle=0x7f9e8ff450
  | state=S schedstat=( 29801302 18298862 79 ) utm=1 stm=0 core=2 HZ=100
  | stack=0x7f9e7fd000-0x7f9e7ff000 stackSize=1037KB
  | held mutexes=
  at java.lang.Object.wait! (Native method)
- waiting on <0x005d09d7> (a java.lang.Object)
  at java.lang.Object.wait (Object.java:407)
  at com.google.android.gms.internal.zzaud$zzd.run (unavailable)

"AsyncTask #1" prio=5 tid=12 TimedWaiting
  | group="main" sCount=1 dsCount=0 obj=0x12eeb5e0 self=0x7f95bdf400
  | sysTid=15998 nice=10 cgrp=default sched=0/0 handle=0x7f98a68450
  | state=S schedstat=( 107492766 149401461 175 ) utm=10 stm=0 core=2 HZ=100
  | stack=0x7f98966000-0x7f98968000 stackSize=1037KB
  | held mutexes=
  at java.lang.Object.wait! (Native method)
- waiting on <0x03e6e2c4> (a java.lang.Object)
  at java.lang.Thread.parkFor$ (Thread.java:2127)
- locked <0x03e6e2c4> (a java.lang.Object)
  at sun.misc.Unsafe.park (Unsafe.java:325)
  at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:201)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos (AbstractQueuedSynchronizer.java:2077)
  at java.util.concurrent.LinkedBlockingQueue.poll (LinkedBlockingQueue.java:438)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1057)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1118)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
  at java.lang.Thread.run (Thread.java:761)

"ModernAsyncTask #1" prio=5 tid=14 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x12f621f0 self=0x7f95be0800
  | sysTid=16000 nice=10 cgrp=default sched=0/0 handle=0x7f987de450
  | state=S schedstat=( 25427040 77349367 115 ) utm=1 stm=0 core=2 HZ=100
  | stack=0x7f986dc000-0x7f986de000 stackSize=1037KB
  | held mutexes=
  at java.lang.Object.wait! (Native method)
- waiting on <0x09fe75ad> (a java.lang.Object)
  at java.lang.Thread.parkFor$ (Thread.java:2127)
- locked <0x09fe75ad> (a java.lang.Object)
  at sun.misc.Unsafe.park (Unsafe.java:325)
  at java.util.concurrent.locks.LockSupport.park (LockSupport.java:161)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2035)
  at java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:413)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1058)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1118)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
  at java.lang.Thread.run (Thread.java:761)

"pool-2-thread-1" prio=5 tid=15 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x12f8b550 self=0x7f85330e00
  | sysTid=16001 nice=0 cgrp=default sched=0/0 handle=0x7f84fff450
  | state=S schedstat=( 4749531 21179951 21 ) utm=0 stm=0 core=3 HZ=100
  | stack=0x7f84efd000-0x7f84eff000 stackSize=1037KB
  | held mutexes=
  at java.lang.Object.wait! (Native method)
- waiting on <0x0a0100e2> (a java.lang.Object)
  at java.lang.Thread.parkFor$ (Thread.java:2127)
- locked <0x0a0100e2> (a java.lang.Object)
  at sun.misc.Unsafe.park (Unsafe.java:325)
  at java.util.concurrent.locks.LockSupport.park (LockSupport.java:161)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2035)
  at java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:413)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1058)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1118)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
  at java.lang.Thread.run (Thread.java:761)

"RenderThread" prio=5 tid=17 Native
  | group="main" sCount=1 dsCount=0 obj=0x12d3a700 self=0x7f95be1200
  | sysTid=16015 nice=-10 cgrp=default sched=0/0 handle=0x7f84aca450
  | state=S schedstat=( 328604740 60940313 458 ) utm=21 stm=11 core=3 HZ=100
  | stack=0x7f849d0000-0x7f849d2000 stackSize=1005KB
  | held mutexes=
  native: pc 0000000000078e28  /system/lib64/libc.so (__epoll_pwait+8)
  native: pc 000000000001e868  /system/lib64/libc.so (epoll_pwait+64)
  native: pc 00000000000183bc  /system/lib64/libutils.so (_ZN7android6Looper9pollInnerEi+160)
  native: pc 0000000000018264  /system/lib64/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+60)
  native: pc 000000000003dc0c  /system/lib64/libhwui.so (_ZN7android10uirenderer12renderthread12RenderThread10threadLoopEv+1028)
  native: pc 000000000001283c  /system/lib64/libutils.so (_ZN7android6Thread11_threadLoopEPv+328)
  native: pc 00000000000a028c  /system/lib64/libandroid_runtime.so (_ZN7android14AndroidRuntime15javaThreadShellEPv+112)
  native: pc 000000000007684c  /system/lib64/libc.so (_ZL15__pthread_startPv+204)
  native: pc 000000000001e158  /system/lib64/libc.so (__start_thread+16)

"pool-3-thread-1" prio=5 tid=18 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x12d3a790 self=0x7f95be2600
  | sysTid=16024 nice=0 cgrp=default sched=0/0 handle=0x7f83fd8450
  | state=S schedstat=( 10177035 8410986 23 ) utm=0 stm=0 core=2 HZ=100
  | stack=0x7f83ed6000-0x7f83ed8000 stackSize=1037KB
  | held mutexes=
  at java.lang.Object.wait! (Native method)
- waiting on <0x017e6c73> (a java.lang.Object)
  at java.lang.Thread.parkFor$ (Thread.java:2127)
- locked <0x017e6c73> (a java.lang.Object)
  at sun.misc.Unsafe.park (Unsafe.java:325)
  at java.util.concurrent.locks.LockSupport.park (LockSupport.java:161)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2035)
  at java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:413)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1058)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1118)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
  at java.lang.Thread.run (Thread.java:761)

"Okio Watchdog" daemon prio=5 tid=19 TimedWaiting
  | group="main" sCount=1 dsCount=0 obj=0x13081af0 self=0x7f98444600
  | sysTid=16042 nice=0 cgrp=default sched=0/0 handle=0x7f7fb97450
  | state=S schedstat=( 419585 2875468 14 ) utm=0 stm=0 core=2 HZ=100
  | stack=0x7f7fa95000-0x7f7fa97000 stackSize=1037KB
  | held mutexes=
  at java.lang.Object.wait! (Native method)
- waiting on <0x0bd16730> (a java.lang.Class<okio.AsyncTimeout>)
  at okio.AsyncTimeout.awaitTimeout (unavailable)
  at okio.AsyncTimeout$Watchdog.run (unavailable)
- locked <0x0bd16730> (a java.lang.Class<okio.AsyncTimeout>)

"OkHttp ConnectionPool" daemon prio=5 tid=20 TimedWaiting
  | group="main" sCount=1 dsCount=0 obj=0x13081430 self=0x7f98443c00
  | sysTid=16041 nice=0 cgrp=default sched=0/0 handle=0x7f809df450
  | state=S schedstat=( 381303 13536249 11 ) utm=0 stm=0 core=2 HZ=100
  | stack=0x7f808dd000-0x7f808df000 stackSize=1037KB
  | held mutexes=
  at java.lang.Object.wait! (Native method)
- waiting on <0x04b9bfa9> (a okhttp3.ConnectionPool)
  at okhttp3.ConnectionPool$1.run (unavailable)
- locked <0x04b9bfa9> (a okhttp3.ConnectionPool)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
  at java.lang.Thread.run (Thread.java:761)

"hwuiTask1" prio=5 tid=21 Native
  | group="main" sCount=1 dsCount=0 obj=0x1311e280 self=0x7f80dbee00
  | sysTid=16048 nice=-2 cgrp=default sched=0/0 handle=0x7f7d737450
  | state=S schedstat=( 5478544 10507343 56 ) utm=0 stm=0 core=3 HZ=100
  | stack=0x7f7d63d000-0x7f7d63f000 stackSize=1005KB
  | held mutexes=
  native: pc 000000000001bd2c  /system/lib64/libc.so (syscall+28)
  native: pc 0000000000075f64  /system/lib64/libc.so (pthread_cond_wait+96)
  native: pc 000000000003ebec  /system/lib64/libhwui.so (???)
  native: pc 0000000000012858  /system/lib64/libutils.so (_ZN7android6Thread11_threadLoopEPv+356)
  native: pc 00000000000a028c  /system/lib64/libandroid_runtime.so (_ZN7android14AndroidRuntime15javaThreadShellEPv+112)
  native: pc 000000000007684c  /system/lib64/libc.so (_ZL15__pthread_startPv+204)
  native: pc 000000000001e158  /system/lib64/libc.so (__start_thread+16)

"hwuiTask2" prio=5 tid=22 Native
  | group="main" sCount=1 dsCount=0 obj=0x1311e310 self=0x7f98517000
  | sysTid=16049 nice=-2 cgrp=default sched=0/0 handle=0x7f7d63a450
  | state=S schedstat=( 2684376 5726561 23 ) utm=0 stm=0 core=3 HZ=100
  | stack=0x7f7d540000-0x7f7d542000 stackSize=1005KB
  | held mutexes=
  native: pc 000000000001bd2c  /system/lib64/libc.so (syscall+28)
  native: pc 0000000000075f64  /system/lib64/libc.so (pthread_cond_wait+96)
  native: pc 000000000003ebec  /system/lib64/libhwui.so (???)
  native: pc 0000000000012858  /system/lib64/libutils.so (_ZN7android6Thread11_threadLoopEPv+356)
  native: pc 00000000000a028c  /system/lib64/libandroid_runtime.so (_ZN7android14AndroidRuntime15javaThreadShellEPv+112)
  native: pc 000000000007684c  /system/lib64/libc.so (_ZL15__pthread_startPv+204)
  native: pc 000000000001e158  /system/lib64/libc.so (__start_thread+16)

"RenderThread" prio=5 (not attached)
  | sysTid=16044 nice=-10 cgrp=default
  | state=S schedstat=( 26510 3279427 2 ) utm=0 stm=0 core=0 HZ=100

"RenderThread" prio=5 (not attached)
  | sysTid=16045 nice=-10 cgrp=default
  | state=S schedstat=( 66459 3187916 2 ) utm=0 stm=0 core=1 HZ=100

"RenderThread" prio=5 (not attached)
  | sysTid=16046 nice=-10 cgrp=default
  | state=S schedstat=( 2715260 5227398 4 ) utm=0 stm=0 core=2 HZ=100

"RenderThread" prio=5 (not attached)
  | sysTid=16047 nice=-10 cgrp=default
  | state=S schedstat=( 2826146 357865 6 ) utm=0 stm=0 core=3 HZ=100

**Comment by jahirfiquitiva** [comment]
1. Don't post logs that long in a GitHub issue. Use pastebin.com for example.
2. Wrap logs and/or code snippets in proper code tags.
3. This issue is completely internal libraries related. If you read the log, there's not a single mention of an IconShowcase component. Therefore, the issue is invalid and impossible to reproduce.
